### ISSUE TITLE
可否将滑动成功的字体颜色修改去除

### ISSUE THREAD

**Issue by weiqishang** [zoux/vue-verify-slider#2]

**Comment by zoux** [comment]
如果需要修改字体颜色，可以直接覆盖样式，如：

```css
.drag_text {
  color: red !important;
}
```

同理其他样式都可以复写。
